name: e_com
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  url_launcher: ^6.2.4
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.6
  fluttertoast: ^8.2.4
  gap: ^3.0.1
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:

  uses-material-design: true

  
  assets:
    - assets/icons/
    - assets/images/
      
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
